version: "3.8"

services:
  app:
    container_name: hokkori_app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "./bin/hokkori"
    environment:
      HOKKORI_ENV:
      HOKKORI_DB_PASSWORD:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"