// Code generated by ent, DO NOT EDIT.

package work

const (
	// Label holds the string label denoting the work type in the database.
	Label = "work"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "posts"
	// EdgeDrafts holds the string denoting the drafts edge name in mutations.
	EdgeDrafts = "drafts"
	// Table holds the table name of the work in the database.
	Table = "works"
	// PostsTable is the table that holds the posts relation/edge.
	PostsTable = "posts"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
	// PostsColumn is the table column denoting the posts relation/edge.
	PostsColumn = "work_posts"
	// DraftsTable is the table that holds the drafts relation/edge.
	DraftsTable = "drafts"
	// DraftsInverseTable is the table name for the Draft entity.
	// It exists in this package in order to avoid circular dependency with the "draft" package.
	DraftsInverseTable = "drafts"
	// DraftsColumn is the table column denoting the drafts relation/edge.
	DraftsColumn = "work_drafts"
)

// Columns holds all SQL columns for work fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldThumbnail,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ThumbnailValidator is a validator for the "thumbnail" field. It is called by the builders before save.
	ThumbnailValidator func(string) error
)
