// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MONAKA0721/hokkori/ent/post"
)

type CreatePostInput struct {
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Type    post.Type `json:"type"`
}

type CreateUserInput struct {
	ID string `json:"id"`
}
