// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/MONAKA0721/hokkori/ent"
)

type BookmarkPostInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	PostID           int     `json:"postID"`
}

type BookmarkPostPayload struct {
	ClientMutationID *string   `json:"clientMutationId"`
	Post             *ent.Post `json:"post"`
}

type LikePostInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	PostID           int     `json:"postID"`
}

type LikePostPayload struct {
	ClientMutationID *string   `json:"clientMutationId"`
	Post             *ent.Post `json:"post"`
}

type UnbookmarkPostInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	PostID           int     `json:"postID"`
}

type UnbookmarkPostPayload struct {
	ClientMutationID *string   `json:"clientMutationId"`
	Post             *ent.Post `json:"post"`
}

type UnlikePostInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	UserID           int     `json:"userID"`
	PostID           int     `json:"postID"`
}

type UnlikePostPayload struct {
	ClientMutationID *string   `json:"clientMutationId"`
	Post             *ent.Post `json:"post"`
}
