// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LettersColumns holds the columns for the "letters" table.
	LettersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
	}
	// LettersTable holds the schema information for the "letters" table.
	LettersTable = &schema.Table{
		Name:       "letters",
		Columns:    LettersColumns,
		PrimaryKey: []*schema.Column{LettersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LettersTable,
	}
)

func init() {
}
