// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/MONAKA0721/hokkori/ent/letter"
	"github.com/MONAKA0721/hokkori/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	letterFields := schema.Letter{}.Fields()
	_ = letterFields
	// letterDescContent is the schema descriptor for content field.
	letterDescContent := letterFields[0].Descriptor()
	// letter.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	letter.ContentValidator = letterDescContent.Validators[0].(func(string) error)
}
