// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Letter is the predicate function for letter builders.
type Letter func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
